<a href="https://colab.research.google.com/github/vtkachuk4/ml_playground/blob/master/mnist_ml_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 0s 0us/step


In [0]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

predictions = model(x_train[:1]).numpy()
predictions

array([[-0.6176604 , -0.06260644,  0.19284573,  0.01235582, -0.24438938,
        -0.01300609,  0.04452439,  0.5137119 , -0.3991286 ,  0.07235046]],
      dtype=float32)

In [0]:
tf.nn.softmax(predictions).numpy()

array([[0.05426308, 0.09452818, 0.12204016, 0.10188659, 0.07881592,
        0.09933504, 0.10521742, 0.16821054, 0.06751676, 0.10818632]],
      dtype=float32)

In [0]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [0]:
loss_fn(y_train[:1], predictions).numpy()

2.309257

In [0]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [0]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2943 - accuracy: 0.9157
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1457 - accuracy: 0.9563
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1105 - accuracy: 0.9664
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0907 - accuracy: 0.9723
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0752 - accuracy: 0.9763


In [0]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0824 - accuracy: 0.9743


[0.0823555514216423, 0.9743000268936157]

In [0]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [0]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.72090173e-08, 7.31796790e-10, 1.43311527e-05, 2.80081604e-05,
        1.77667617e-10, 5.28363557e-07, 2.54069574e-12, 9.99956489e-01,
        7.57020118e-08, 6.58067165e-07],
       [1.95117589e-09, 4.40244516e-03, 9.95518923e-01, 7.58399547e-05,
        1.57492790e-18, 2.55747068e-06, 9.53118047e-08, 1.17681108e-11,
        1.50553348e-07, 9.97449041e-18],
       [4.96911639e-07, 9.98782694e-01, 1.04304614e-04, 2.97360275e-05,
        1.96244036e-05, 1.98904891e-05, 5.57056810e-05, 7.03362282e-04,
        2.83389294e-04, 8.08262769e-07],
       [9.99962687e-01, 1.02940975e-10, 3.38504833e-05, 3.11038389e-10,
        1.84822913e-08, 4.22788986e-07, 2.38976168e-06, 2.32807210e-07,
        1.21659560e-09, 3.84250995e-07],
       [4.58355316e-06, 1.55662316e-09, 7.86283238e-07, 1.96487662e-08,
        9.99255836e-01, 1.68570210e-07, 1.39055519e-05, 3.17328631e-05,
        1.40179949e-07, 6.92902307e-04]], dtype=float32)>